apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    editable: false

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
    editable: false

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-service:5432
    database: trading_db
    user: trading
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: require
      postgresVersion: 1600
      timescaledb: false
    editable: false

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-service:6379
    secureJsonData:
      password: $REDIS_PASSWORD
    jsonData:
      poolSize: 10
      timeout: 10
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[trading-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "7.10+"
      logMessageField: message
      logLevelField: level
    editable: false