global:
  resolve_timeout: 5m
  slack_api_url: 'SLACK_WEBHOOK_URL'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
  # Critical alerts - immediate notification
  - match:
      severity: critical
    receiver: 'critical'
    continue: true
    routes:
    - match:
        team: trading
      receiver: 'trading-critical'
    - match:
        team: security
      receiver: 'security-critical'
  
  # Warning alerts - batched
  - match:
      severity: warning
    receiver: 'warning'
    group_wait: 5m
    group_interval: 5m
    repeat_interval: 4h
  
  # Compliance alerts
  - match:
      team: compliance
    receiver: 'compliance'
    group_wait: 30m
    repeat_interval: 24h

receivers:
- name: 'default'
  slack_configs:
  - channel: '#alerts'
    title: 'Alert: {{ .GroupLabels.alertname }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    send_resolved: true

- name: 'critical'
  pagerduty_configs:
  - service_key: 'PAGERDUTY_SERVICE_KEY'
    description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
    details:
      firing: '{{ .Alerts.Firing | len }}'
      resolved: '{{ .Alerts.Resolved | len }}'
      alerts: '{{ range .Alerts }}{{ .Labels.instance }}: {{ .Annotations.description }}{{ end }}'
  slack_configs:
  - channel: '#critical-alerts'
    title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    text: '{{ .CommonAnnotations.description }}'
    color: 'danger'
    send_resolved: true
  email_configs:
  - to: 'oncall@company.com'
    from: 'alerts@company.com'
    smarthost: 'smtp.company.com:587'
    auth_username: 'alerts@company.com'
    auth_password: 'EMAIL_PASSWORD'
    headers:
      Subject: 'CRITICAL: {{ .GroupLabels.alertname }}'

- name: 'trading-critical'
  pagerduty_configs:
  - service_key: 'TRADING_PAGERDUTY_KEY'
    description: 'Trading Alert: {{ .CommonAnnotations.summary }}'
  slack_configs:
  - channel: '#trading-alerts'
    title: '💹 Trading Critical: {{ .GroupLabels.alertname }}'
    text: '{{ .CommonAnnotations.description }}'
    color: 'danger'
    actions:
    - type: button
      text: 'View Runbook'
      url: '{{ .CommonAnnotations.runbook_url }}'
    - type: button
      text: 'View Dashboard'
      url: 'https://grafana.company.com/d/trading-overview'

- name: 'security-critical'
  pagerduty_configs:
  - service_key: 'SECURITY_PAGERDUTY_KEY'
    description: 'Security Alert: {{ .CommonAnnotations.summary }}'
  slack_configs:
  - channel: '#security-alerts'
    title: '🔐 Security Alert: {{ .GroupLabels.alertname }}'
    text: '{{ .CommonAnnotations.description }}'
    color: 'danger'
  email_configs:
  - to: 'security@company.com'
    headers:
      Subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
      Priority: 'urgent'

- name: 'warning'
  slack_configs:
  - channel: '#alerts'
    title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
    text: '{{ .CommonAnnotations.description }}'
    color: 'warning'
    send_resolved: true

- name: 'compliance'
  email_configs:
  - to: 'compliance@company.com'
    from: 'alerts@company.com'
    headers:
      Subject: 'Compliance Alert: {{ .GroupLabels.alertname }}'
  slack_configs:
  - channel: '#compliance'
    title: '📋 Compliance: {{ .GroupLabels.alertname }}'
    text: '{{ .CommonAnnotations.description }}'

inhibit_rules:
  # Inhibit warnings when there's a critical alert for the same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  
  # Inhibit all alerts when the entire cluster is down
  - source_match:
      alertname: 'ClusterDown'
    target_match_re:
      alertname: '.*'
    equal: ['cluster']