apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-bot-config
  namespace: trading
  labels:
    app: crypto-trading-bot
data:
  config.yaml: |
    application:
      name: crypto-trading-bot
      environment: production
      version: 1.0.0
    
    server:
      host: 0.0.0.0
      port: 8080
      workers: 4
      timeout: 30
    
    logging:
      level: INFO
      format: json
      output: stdout
      structured: true
      fields:
        - timestamp
        - level
        - message
        - trace_id
        - span_id
        - pod_name
        - namespace
    
    metrics:
      enabled: true
      port: 9090
      path: /metrics
      include_default: true
    
    trading:
      enabled: true
      mode: live
      max_positions: 10
      risk_percentage: 2.0
      stop_loss_percentage: 5.0
      take_profit_percentage: 10.0
      
    exchange:
      name: kraken
      api_version: v2
      websocket_enabled: true
      rate_limit:
        calls_per_second: 10
        burst: 20
      timeout: 30
      retry:
        max_attempts: 3
        backoff_seconds: 1
    
    database:
      pool_size: 20
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 3600
      echo: false
    
    redis:
      pool_size: 10
      decode_responses: true
      socket_timeout: 5
      socket_connect_timeout: 5
      retry_on_timeout: true
    
    monitoring:
      health_check_interval: 30
      metrics_interval: 60
      alerting:
        enabled: true
        channels:
          - slack
          - email
          - pagerduty
    
    features:
      circuit_breaker: true
      rate_limiting: true
      request_validation: true
      response_caching: true
      distributed_tracing: true
    
  trading-pairs.yaml: |
    pairs:
      - symbol: BTC/USD
        enabled: true
        min_order_size: 0.0001
        max_order_size: 10.0
        precision: 8
        strategies:
          - mean_reversion
          - momentum
      
      - symbol: ETH/USD
        enabled: true
        min_order_size: 0.001
        max_order_size: 100.0
        precision: 8
        strategies:
          - mean_reversion
          - scalping
      
      - symbol: SOL/USD
        enabled: true
        min_order_size: 0.1
        max_order_size: 1000.0
        precision: 6
        strategies:
          - momentum
          - arbitrage
    
  strategies.yaml: |
    strategies:
      mean_reversion:
        enabled: true
        window_size: 20
        deviation_threshold: 2.0
        position_size: 0.1
        
      momentum:
        enabled: true
        fast_ma: 12
        slow_ma: 26
        signal_ma: 9
        position_size: 0.15
        
      scalping:
        enabled: true
        tick_size: 0.01
        profit_target: 0.002
        stop_loss: 0.001
        position_size: 0.2
        
      arbitrage:
        enabled: false
        min_spread: 0.001
        execution_time: 100
        position_size: 0.25